name: Update Data

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false # Required to make GitHub forget this authentication

    - name: Run update script
      run: ./update.sh

    - name: Commit and push changes
      run: |
        git config user.name "Automated Update"
        git config user.email "your-email@example.com"
        git add -A
        if [[ -n $(git status -s) ]]; then
          git commit -m "Automated data update"
          git push
        else
          echo "No changes to commit"
          exit 0
        fi

    - name: Notify Discord
      if: always()  # This ensures the step is run even if previous steps fail
      run: |
        MESSAGE="Data update job completed. Status: ${{ job.status }}."
        curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"$MESSAGE\"}" ${{ secrets.DISCORD_WEBHOOK_URL }}
